# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0006_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='object_id',
            field=models.CharField(default='', help_text='Please enter the ID of the related object.', max_length=255, verbose_name='Related object'),
        ),
        migrations.AlterField(
            model_name='like',
            name='owner_object_id',
            field=models.CharField(default='', help_text='Please enter the ID of the related object.', max_length=255, verbose_name='Owner'),
        ),
    ]
